name: Pack

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Pack using HEMTT
        uses: arma-actions/hemtt@master
        with:
          command: pack --release --ci
      - name: Upload Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: ARC_MISC-${{ github.sha }}-nobin
          path: releases/ARC_MISC_*.zip
